import { ErroCodes } from "../enums/error-codes.js";

export const ErrorMessages = {
    [ErroCodes.USER_UNAUTHORIZED]: "O e-mail ou senha informados estão incorretos (cod.: 401001)",
    [ErroCodes.USER_ALREADY_EXISTS]: "O e-mail informado já está cadastrado (cod.: 400002)",
    [ErroCodes.TOKEN_NOT_PROVIDED]: "Token não fornecido (cod.: 401003)",
    [ErroCodes.TOKEN_INVALID]: "Token inválido (cod.: 401004)",
    [ErroCodes.TOKEN_EXPIRED]: "Token expirado (cod.: 401005)",
    [ErroCodes.TOKEN_NOT_FOUND]: "Token não encontrado (cod.: 401006)",
    [ErroCodes.USER_PASSWORD_REQUIRED]: "A senha é obrigatória (cod.: 400007)",
    [ErroCodes.USER_NAME_REQUIRED]: "O nome é obrigatório (cod.: 400008)",
    [ErroCodes.USER_EMAIL_REQUIRED]: "O e-mail é obrigatório (cod.: 400009)",
    [ErroCodes.USER_NAME_MIN_LENGTH]: "O nome deve ter pelo menos 3 caracteres (cod.: 400010)",
    [ErroCodes.USER_EMAIL_MIN_LENGTH]: "O e-mail deve ter pelo menos 3 caracteres (cod.: 400011)",
    [ErroCodes.USER_PASSWORD_MIN_LENGTH]: "A senha deve ter pelo menos 6 caracteres (cod.: 400012)",
    [ErroCodes.USER_EMAIL_INVALID]: "O e-mail informado é inválido (cod.: 400013)",
    [ErroCodes.USER_NAME_INVALID]: "O nome informado é inválido (cod.: 400014)",
    [ErroCodes.USER_NOT_FOUND]: "Usuário não encontrado (cod.: 400015)",
    [ErroCodes.USER_ID_REQUIRED]: "O id do usuário é obrigatório (cod.: 400016)",
    [ErroCodes.USER_EMAIL_NOT_FOUND]: "O e-mail informado não foi encontrado (cod.: 400017)",
    [ErroCodes.CLIENT_NAME_REQUIRED]: "O nome do cliente é obrigatório (cod.: 400018)",
    [ErroCodes.CLIENT_EMAIL_REQUIRED]: "O e-mail do cliente é obrigatório (cod.: 400019)",
    [ErroCodes.CLIENT_EMAIL_INVALID]: "O e-mail do cliente é inválido (cod.: 400020)",
    [ErroCodes.CLIENT_DOCUMENT_REQUIRED]: "O documento do cliente é obrigatório (cod.: 400021)",
    [ErroCodes.CLIENT_ALREADY_EXISTS]: "Já existe um cliente cadastrado com este e-mail (cod.: 400022)",
    [ErroCodes.CLIENT_NOT_FOUND]: "Cliente não encontrado (cod.: 400023)",
    [ErroCodes.CLIENT_ID_REQUIRED]: "O id do cliente é obrigatório (cod.: 400024)",
    [ErroCodes.CLIENT_PHONE_REQUIRED]: "O telefone do cliente é obrigatório (cod.: 400025)",
    [ErroCodes.CLIENT_PAGE_REQUIRED]: "A página é obrigatória (cod.: 400026)",
    [ErroCodes.CLIENT_PAGE_MAX]: "A página deve ter no máximo 50 caracteres (cod.: 400027)",
    [ErroCodes.CLIENT_LIMIT_REQUIRED]: "O limite é obrigatório (cod.: 400028)",
    [ErroCodes.CLIENT_LIMIT_MAX]: "O limite deve ter no máximo 100 caracteres (cod.: 400029)",
    [ErroCodes.CLIENT_PAGE_INVALID]: "A página deve ser um número (cod.: 400030)",
    [ErroCodes.CLIENT_LIMIT_INVALID]: "O limite deve ser um número (cod.: 400031)",
    [ErroCodes.VENDOR_NAME_REQUIRED]: "O nome do fornecedor é obrigatório (cod.: 400032)",
    [ErroCodes.VENDOR_EMAIL_REQUIRED]: "O e-mail do fornecedor é obrigatório (cod.: 400033)",
    [ErroCodes.VENDOR_EMAIL_INVALID]: "O e-mail do fornecedor é inválido (cod.: 400034)",
    [ErroCodes.VENDOR_DOCUMENT_REQUIRED]: "O documento do fornecedor é obrigatório (cod.: 400035)",
    [ErroCodes.VENDOR_ALREADY_EXISTS]: "Já existe um fornecedor cadastrado com este e-mail (cod.: 400036)",
    [ErroCodes.VENDOR_NOT_FOUND]: "Fornecedor não encontrado (cod.: 400037)",
    [ErroCodes.VENDOR_ID_REQUIRED]: "O id do fornecedor é obrigatório (cod.: 400038)",
    [ErroCodes.VENDOR_PHONE_REQUIRED]: "O telefone do fornecedor é obrigatório (cod.: 400039)",
    [ErroCodes.VENDOR_PAGE_REQUIRED]: "A página do fornecedor é obrigatória (cod.: 400040)",
    [ErroCodes.VENDOR_PAGE_MAX]: "A página do fornecedor deve ter no máximo 50 caracteres (cod.: 400041)",
    [ErroCodes.VENDOR_LIMIT_REQUIRED]: "O limite do fornecedor é obrigatório (cod.: 400042)",
    [ErroCodes.VENDOR_LIMIT_MAX]: "O limite do fornecedor deve ter no máximo 100 caracteres (cod.: 400043)",
    [ErroCodes.VENDOR_PAGE_INVALID]: "A página do fornecedor deve ser um número (cod.: 400044)",
    [ErroCodes.VENDOR_LIMIT_INVALID]: "O limite do fornecedor deve ser um número (cod.: 400045)",
    [ErroCodes.PRODUCT_NAME_REQUIRED]: "O nome do produto é obrigatório (cod.: 400046)",
    [ErroCodes.PRODUCT_COST_PRICE_REQUIRED]: "O preço de custo é obrigatório (cod.: 400047)",
    [ErroCodes.PRODUCT_SELL_PRICE_REQUIRED]: "O preço de venda é obrigatório (cod.: 400048)",
    [ErroCodes.PRODUCT_ALREADY_EXISTS]: "Já existe um produto cadastrado com este nome (cod.: 400049)",
    [ErroCodes.PRODUCT_NOT_FOUND]: "Produto não encontrado (cod.: 400050)",
    [ErroCodes.PRODUCT_ID_REQUIRED]: "O id do produto é obrigatório (cod.: 400051)",
    [ErroCodes.PRODUCT_PAGE_REQUIRED]: "A página é obrigatória (cod.: 400052)",
    [ErroCodes.PRODUCT_PAGE_MAX]: "A página deve ter no máximo 50 (cod.: 400053)",
    [ErroCodes.PRODUCT_LIMIT_REQUIRED]: "O limite é obrigatório (cod.: 400054)",
    [ErroCodes.PRODUCT_LIMIT_MAX]: "O limite deve ter no máximo 100 (cod.: 400055)",
    [ErroCodes.PRODUCT_PAGE_INVALID]: "A página deve ser um número (cod.: 400056)",
    [ErroCodes.PRODUCT_LIMIT_INVALID]: "O limite deve ser um número (cod.: 400057)",
    [ErroCodes.SERVICE_NAME_REQUIRED]: "O nome do serviço é obrigatório (cod.: 400058)",
    [ErroCodes.SERVICE_PRICE_REQUIRED]: "O preço do serviço é obrigatório (cod.: 400059)",
    [ErroCodes.SERVICE_ALREADY_EXISTS]: "Já existe um serviço cadastrado com este nome (cod.: 400060)",
    [ErroCodes.SERVICE_NOT_FOUND]: "Serviço não encontrado (cod.: 400061)",
    [ErroCodes.SERVICE_ID_REQUIRED]: "O id do serviço é obrigatório (cod.: 400062)",
    [ErroCodes.SERVICE_PAGE_REQUIRED]: "A página é obrigatória (cod.: 400063)",
    [ErroCodes.SERVICE_PAGE_MAX]: "A página deve ter no máximo 50 (cod.: 400064)",
    [ErroCodes.SERVICE_LIMIT_REQUIRED]: "O limite é obrigatório (cod.: 400065)",
    [ErroCodes.SERVICE_LIMIT_MAX]: "O limite deve ter no máximo 100 (cod.: 400066)",
    [ErroCodes.SERVICE_PAGE_INVALID]: "A página deve ser um número (cod.: 400067)",
    [ErroCodes.SERVICE_LIMIT_INVALID]: "O limite deve ser um número (cod.: 400068)",
    [ErroCodes.SERVICE_ORDER_CLIENT_ID_REQUIRED]: "O client_id da ordem de serviço é obrigatório (cod.: 400069)",
    [ErroCodes.SERVICE_ORDER_DESCRIPTION_REQUIRED]: "A descrição da ordem de serviço é obrigatória (cod.: 400070)",
    [ErroCodes.SERVICE_ORDER_SERVICE_ID_REQUIRED]: "O service_id da ordem de serviço é obrigatório (cod.: 400071)",
    [ErroCodes.SERVICE_ORDER_PRODUCT_ID_REQUIRED]: "O product_id da ordem de serviço é obrigatório (cod.: 400072)",
    [ErroCodes.SERVICE_ORDER_STATUS_REQUIRED]: "O status do serviço é obrigatório (cod.: 400073)",
    [ErroCodes.SERVICE_ORDER_INVALID_STATUS]: "O status do serviço é inválido (cod.: 400074)",
    [ErroCodes.SERVICE_ORDER_NOT_FOUND]: "Ordem de serviço não encontrada (cod.: 400075)",
    [ErroCodes.SERVICE_ORDER_ID_REQUIRED]: "O id da ordem de serviço é obrigatório (cod.: 400076)",
    [ErroCodes.SERVICE_ORDER_PAGE_REQUIRED]: "A página é obrigatória (cod.: 400077)",
    [ErroCodes.SERVICE_ORDER_PAGE_MAX]: "A página deve ter no máximo 50 (cod.: 400078)",
    [ErroCodes.SERVICE_ORDER_LIMIT_REQUIRED]: "O limite é obrigatório (cod.: 400079)",
    [ErroCodes.SERVICE_ORDER_LIMIT_MAX]: "O limite deve ter no máximo 100 (cod.: 400080)",
    [ErroCodes.SERVICE_ORDER_PAGE_INVALID]: "A página deve ser um número (cod.: 400081)",
    [ErroCodes.SERVICE_ORDER_LIMIT_INVALID]: "O limite deve ser um número (cod.: 400082)",
    [ErroCodes.USER_CONFIRM_PASSWORD_REQUIRED]: "A confirmação de senha é obrigatória (cod.: 400083)",
    [ErroCodes.USER_PASSWORDS_DO_NOT_MATCH]: "Senha e confirmação de senha não coincidem (cod.: 400084)",
    [ErroCodes.COMPANY_DOCUMENT_REQUIRED]: "O documento da empresa é obrigatório (cod.: 400085)",
    [ErroCodes.COMPANY_EMAIL_REQUIRED]: "O e-mail da empresa é obrigatório (cod.: 400086)",
    [ErroCodes.COMPANY_EMAIL_INVALID]: "O e-mail da empresa é inválido (cod.: 400087)",
    [ErroCodes.COMPANY_PHONE_REQUIRED]: "O telefone da empresa é obrigatório (cod.: 400088)",
    [ErroCodes.COMPANY_ALREADY_EXISTS]: "Já existe uma empresa cadastrada com este e-mail (cod.: 400089)",
    [ErroCodes.COMPANY_NOT_FOUND]: "Empresa não encontrada (cod.: 400090)",
    [ErroCodes.COMPANY_ID_REQUIRED]: "O id da empresa é obrigatório (cod.: 400091)",
    [ErroCodes.COMPANY_PAGE_REQUIRED]: "A página é obrigatória (cod.: 400092)",
    [ErroCodes.COMPANY_PAGE_MAX]: "A página deve ter no máximo 50 (cod.: 400093)",
    [ErroCodes.COMPANY_LIMIT_REQUIRED]: "O limite é obrigatório (cod.: 400094)",
    [ErroCodes.COMPANY_LIMIT_MAX]: "O limite deve ter no máximo 100 (cod.: 400095)",
    [ErroCodes.COMPANY_PAGE_INVALID]: "A página deve ser um número (cod.: 400096)",
    [ErroCodes.COMPANY_LIMIT_INVALID]: "O limite deve ser um número (cod.: 400097)",
    [ErroCodes.COMPANY_ID_NOT_PROVIDED]: "O id da empresa (company_id) é obrigatório e deve ser informado no header x-company-id (cod.: 400098)",
    [ErroCodes.COMPANY_ID_INVALID]: "O id da empresa (company_id) informado é inválido (cod.: 400099)",
    [ErroCodes.PASSWORD_REQUIRED]: "A senha é obrigatória (cod.: 400100)",
    [ErroCodes.CONFIRM_PASSWORD_REQUIRED]: "A confirmação de senha é obrigatória (cod.: 400101)",
    [ErroCodes.PASSWORDS_DO_NOT_MATCH]: "Senha e confirmação de senha não coincidem (cod.: 400102)",
}
