export enum ErroCodes {
    USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
    USER_PASSWORD_REQUIRED = "USER_PASSWORD_REQUIRED",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    TOKEN_NOT_PROVIDED = "TOKEN_NOT_PROVIDED",
    TOKEN_INVALID = "TOKEN_INVALID",
    TOKEN_EXPIRED = "TOKEN_EXPIRED",
    TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
}